#!/bin/bash

##The SNP alignment generated by MultiVCFAnalyzer can be used directly by RAxML or
##trimmed down in MEGA for a complete deletion or partial deletion alignment by removing
##sites that have a minimum threshold of coverage.
##For this project, RAxML was run as follows.

/path/to/standard-RAxML-master/raxmlHPC-HYBRID-AVX -s /path/to/alignment.fasta -n name_of_output_files -w /path/to/output/directory -m GTRGAMMA -f a -p 711374 -x 21873 -N 1000 -T 8 
